# Generated by Django 5.2.6 on 2025-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0006_calculation_chathistory_product_alter_orderitem_dish_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClearPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_cleared",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Соңғы тазалау уақыты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тазалау нүктесі",
                "verbose_name_plural": "Тазалау нүктесі",
            },
        ),
    ]
